export default {
  uploadNewWatch: "Upload a new watch",
  brand: "Brand",
  model: "Model",
  housing: "Case",
  bracelet: "Bracelet",
  dial: "Dial",
  diameter: "Diameter",
  movement: "Movement",
  complications: "Complications",
  price: "Price",
  description: "Description",
  inStock: "In Stock?",
  image: "Image",
  submit: "Submit",
  housingOptions: [
    "Steel",
    "Yellow Gold",
    "White Gold",
    "Rose Gold",
    "Platinum",
    "Titanium",
    "Carbon",
  ],
  braceletOptions: ["Metal", "Leather", "Rubber", "Nato"],
  dialOptions: [
    "White",
    "Black",
    "Blue",
    "Brown",
    "Champagne",
    "Green",
    "Purple",
    "Grey",
    "Skeleton",
  ],
  diameterOptions: [
    "24mm",
    "25mm",
    "26mm",
    "27mm",
    "28mm",
    "29mm",
    "30mm",
    "31mm",
    "32mm",
    "33mm",
    "34mm",
    "35mm",
    "36mm",
    "37mm",
    "38mm",
    "39mm",
    "40mm",
    "41mm",
    "42mm",
    "43mm",
    "44mm",
  ],
  movementOptions: ["Automatic", "Manual", "Quartz"],
  date: "Date",
  annualCalendar: "Annual Calendar",
  perpetualCalendar: "Perpetual Calendar",
  chronograph: "Chronograph",
  gmt: "GMT",
  worldTime: "World Time",
  minuteRepeater: "Minute Repeater",
  moonPhase: "Moon Phase",
  tourbillon: "Tourbillon",
  powerReserve: "Power Reserve",
};
