export default {
  brands: "Brands",
  keys: {
    rolex: "rolex",
    omega: "omega",
    patek: "patek",
    audemars: "audemars",
    cartier: "cartier",
    vacheron: "vacheron",
    breguet: "breguet",
    chopard: "chopard",
    panerai: "panerai",
    mille: "mille",
  },
  accessibility: {
    rolexLogo: "Rolex logo",
    omegaLogo: "Omega logo",
    patekLogo: "Patek Philippe logo",
    audemarsLogo: "Audemars Piguet logo",
    cartierLogo: "Cartier logo",
    vacheronLogo: "Vacheron Constantin logo",
    breguetLogo: "Breguet logo",
    chopardLogo: "Chopard logo",
    paneraiLogo: "Panerai logo",
    milleLogo: "Richard Mille logo",
  },
};
