export default {
  api: {
    SIGN_UP: "/api/users/signUp",
    SIGN_IN: "/api/users/signIn",
    WATCHES: "/api/watches",
    NEW_WATCH: "/newWatch",
  },
  routes: {
    HOME: "/",
    SIGN_UP_SUCCESS: "/signUpSuccess",
    DASHBOARD: "/dashboard",
    SIGN_UP: "/signUp",
    SIGN_IN: "/signIn",
    ABOUT: "/About",
    CONTACT: "/Contact",
    CART: "/Cart",
    BRANDS: "/brands",
    ADMIN: "/Admin",
    SELECTED_BRAND: "/selectedBrand",
    PARAM_BRAND: "/:brand",
    PRODUCT: "/product",
    PARAM_ID: "/:_id",
    UNDER_CONSTRUCTION: "/underConstruction",
    ROLEX: "/Rolex",
    CARTIER: "/Cartier",
    BREGUET: "/Breguet",
    PATEK_PHILIPPE: "/Patek Philippe",
    OMEGA: "/Omega",
    AUDEMARS_PIGUET: "/Audemars Piguet",
    VACHERON_CONSTANTIN: "/Vacheron Constantin",
    CHOPARD: "/Chopard",
    PANERAI: "/Panerai",
    RICHARD_MILLE: "/Richard Mille",
  },
  brands: {
    ROLEX: "Rolex",
    CARTIER: "Cartier",
    BREGUET: "Breguet",
    PATEK_PHILIPPE: "Patek Philippe",
    OMEGA: "Omega",
    AUDEMARS_PIGUET: "Audemars Piguet",
    VACHERON_CONSTANTIN: "Vacheron Constantin",
    CHOPARD: "Chopard",
    PANERAI: "Panerai",
    RICHARD_MILLE: "Richard Mille",
  },
  JWT_TOKEN: "jwtToken",
};
