export default {
  api: {
    SIGN_UP: "/api/users/signUp",
    SIGN_IN: "/api/users/signIn",
    WATCHES: "/api/watches",
  },
  routes: {
    HOME: "/",
    SIGN_UP_SUCCESS: "/signUpSuccess",
    DASHBOARD: "/dashboard",
    SIGN_UP: "/signUp",
    SIGN_IN: "/signIn",
    BRANDS: "/brands",
    DYNAMIC_BRAND: "/dynamicBrand",
    PARAM_BRAND: "/:brand",
    PRODUCT: "/product",
    PARAM_MODEL: "/:model",
    ROLEX: "/Rolex",
    CARTIER: "/Cartier",
    BREGUET: "/Breguet",
    PATEK_PHILIPPE: "/Patek Philippe",
  },
  brands: {
    ROLEX: "Rolex",
    CARTIER: "Cartier",
    BREGUET: "Breguet",
    PATEK_PHILIPPE: "Patek Philippe",
  },
  JWT_TOKEN: "jwtToken",
};
