export default {
  Rolex: [
    "Oyster Perpetual",
    "Datejust",
    "Pearlmaster",
    "Lady-Datejust",
    "Day-Date",
    "Submariner",
    "Cosmograph Daytona",
    "GMT-Master II",
    "Sky-Dweller",
    "Yacht-Master",
    "Sea Dweller",
    "Milgauss",
    "Explorer",
    "Air-King",
    "Cellini",
  ],
  Cartier: [
    "Santos De Cartier",
    "Tank",
    "Drive De Cartier",
    "Ballon Bleau De Cartier",
    "Ronde De Cartier",
    "Cle De Cartier",
    "Retonde De Cartier",
    "Panthere De Cartier",
    "Baignoire",
    "Hypnose",
  ],
  Breguet: [
    "Tradition",
    "Classique",
    "Classique complications",
    "Marine",
    "Heritage",
    "Type XX - XXI - XXII",
    "Reine de Naples",
    "High Jewellery",
  ],
  PatekPhilippe: [
    "Grand Complications",
    "Complications",
    "Calatrava",
    "Gondolo",
    "Golden Ellipse",
    "Nautilus",
    "Aquanaut",
    "Twenty-4",
  ],
  AudemarsPiguet: [
    "Code 11.59",
    "[Re]master01",
    "Royal Oak",
    "Royal Oak Offshore",
    "Royal Oak Concept",
    "Millenary",
    "Jules Audemars",
    "Haute Joaillerie",
  ],
  Omega: ["Constellation", "Seamaster", "Speedmaster", "De Ville"],
  VacheronConstantin: [
    "Patrimony",
    "Traditionnelle",
    "Fiftysix",
    "Overseas",
    "Egerie",
    "Historiques",
    "Metiers d'Art",
  ],
  Chopard: [
    "Alpine Eagle",
    "L.U.C",
    "Classic Racing",
    "Classic",
    "Happy Sport",
    "Happy Diamonds",
    "L'Heure Du Diamant",
    "Imperiale",
    "Ice Cube",
    "La Strada",
  ],
  Panerai: ["Submersible", "Luminor", "Luminor Due", "Radiomir"],
  RichardMille: [
    "BonBon",
    "RM 70-01",
    "RM 67-02",
    "RM 67-01",
    "RM 63-02",
    "RM 63-01",
    "RM 62-01",
    "RM 61-01",
    "RM 60-01",
    "RM 58-01",
    "RM 67-02",
    "RM 055",
    "RM 53-01",
    "RM 52-05",
    "RM 50-04",
    "RM 50-03",
    "RM 50-02",
    "RM 39-01",
    "RM 039",
    "RM 38-01",
    "RM 36-01",
    "RM 35-02",
    "RM 33-02",
    "RM 033",
    "RM 032",
    "RM 031",
    "RM 030",
    "RM 029",
    "RM 028",
    "RM 27-03",
    "RM 25-01",
    "RM 025",
    "RM 023",
    "RM 022",
    "RM 17-01",
    "RM 017",
    "RM 016",
    "RM 015",
    "RM 014",
    "RM 11-04",
    "RM 11-03",
    "RM 11-02",
    "RM 11-01",
    "RM 010",
    "RM 008-V2",
    "RM 004-V3",
    "RM 003-V2",
    "RM 71-01",
    "RM 51-02",
    "RM 037",
    "RM 19-02",
    "RM 19-01",
    "RM 019",
    "RM 11-01",
    "RM 07-01",
  ],
};
