export default {
  masterContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  subNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "1000px",
    height: "30px",
  },
  subNavBtnWrapper: {
    height: "30px",
    display: "flex",
    width: "600px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subNavBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textDecoration: "none",
    height: "30px",
    padding: "0px 10px",
    color: "#444",
  },
  warranty: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#777",
    marginRight: "10px",
  },
  carouselWrapper: {
    width: "1000px",
    height: "600px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "pink",
    marginTop: "10px",
  },
  descriptionWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "1000px",
    margin: "10px",
    color: "#444",
    textAlign: "center",
  },
};
