import colors from "../../colors";

export default {
  masterWrapper: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  subNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "1000px",
    height: "30px",
  },
  subNavBtnWrapper: {
    height: "30px",
    display: "flex",
    width: "600px",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subNavBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textDecoration: "none",
    height: "30px",
    padding: "0px 10px",
    color: colors.darkText,
  },
  warranty: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: colors.lightText,
    marginRight: "10px",
  },
  carouselWrapper: {
    width: "1000px",
    height: "600px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "10px",
  },
  descriptionTitle: {
    display: "flex",
    alignItems: "center",
    width: "1000px",
    color: colors.darkText,
    fontSize: "30px",
    marginTop: "15px",
  },
  descriptionWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "1000px",
    color: colors.darkText,
    textAlign: "center",
    margin: "20px 0px",
  },
};
